//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Top_2000.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artiest> Artiest { get; set; }
        public virtual DbSet<Lijst> Lijst { get; set; }
        public virtual DbSet<Song> Song { get; set; }
    
        public virtual int Import(Nullable<short> yEAR, Nullable<short> pOSITION, string aRTIST, string tITLE, Nullable<short> pUBYEAR)
        {
            var yEARParameter = yEAR.HasValue ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(short));
    
            var pOSITIONParameter = pOSITION.HasValue ?
                new ObjectParameter("POSITION", pOSITION) :
                new ObjectParameter("POSITION", typeof(short));
    
            var aRTISTParameter = aRTIST != null ?
                new ObjectParameter("ARTIST", aRTIST) :
                new ObjectParameter("ARTIST", typeof(string));
    
            var tITLEParameter = tITLE != null ?
                new ObjectParameter("TITLE", tITLE) :
                new ObjectParameter("TITLE", typeof(string));
    
            var pUBYEARParameter = pUBYEAR.HasValue ?
                new ObjectParameter("PUBYEAR", pUBYEAR) :
                new ObjectParameter("PUBYEAR", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Import", yEARParameter, pOSITIONParameter, aRTISTParameter, tITLEParameter, pUBYEARParameter);
        }
    
        public virtual ObjectResult<spGetListByYear_Result> spGetListByYear(Nullable<int> yEAR)
        {
            var yEARParameter = yEAR.HasValue ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetListByYear_Result>("spGetListByYear", yEARParameter);
        }
    
        public virtual ObjectResult<spGetSongsByYear_Result> spGetSongsByYear(Nullable<int> yEAR)
        {
            var yEARParameter = yEAR.HasValue ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetSongsByYear_Result>("spGetSongsByYear", yEARParameter);
        }
    }
}
